### ISSUE TITLE
页面跳转直接就是IP？

### ISSUE THREAD

**Issue by defshine** [react-china/nav.react-china.org#1]
React 文档中文翻译 这个页面跳转是IP啊

**Comment by fraserxu** [comment]
因为http://reactjs.cn/ 这个还没做解析.

**Comment by tiye** [comment]
在这个项目跟进吧:
https://github.com/reactjs-cn/react-docs

**Comment by defshine** [comment]
看了一下 两拨人在搞  这不是两个react社区么?

**Comment by tiye** [comment]
可以这么说, 不过我们都不是官方的~
